name:                shaunwhite
version:             0.1.0.0
github:              "typesafety/shaunwhite"
license:             MIT
author:              "Thomas Li"
maintainer:          "guslithd@student.gu.se"
copyright:           "2021 Thomas Li"

extra-source-files:
- README.md
- CHANGELOG.md

dependencies:
# Prelude dependency
- base
- relude

# Other dependencies
- calamity
- calamity-commands
- di
- di-polysemy
- directory
- filepath
- parseargs
- polysemy
- polysemy-plugin
- text

executables:
  shaunwhite-exe:
    main: Main.hs
    source-dirs: app
    dependencies:
    - shaunwhite
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -flate-specialise
    - -fspecialise-aggressively

# The majority of the code resides here, and is only separated from the
# "executables" to make Haddock generation easier.
library:
  source-dirs: lib/
  exposed-modules:
    - Config

default-extensions:
# Disable implicit Prelude imports. Import the Relude module(s) explicitly
# instead.
- NoImplicitPrelude

- DataKinds
- FlexibleContexts
- GADTs
- ImportQualifiedPost
- LambdaCase
- OverloadedLabels
- OverloadedStrings
- PolyKinds
- RankNTypes
- ScopedTypeVariables
- TypeApplications
- TypeFamilies
- TypeOperators

ghc-options:
# Warnings
- -Wall
- -Wcompat
- -Wincomplete-uni-patterns
- -Wincomplete-record-updates
- -Widentities
- -Wmissing-export-lists
- -Wpartial-fields
- -Wredundant-constraints

# Plugin for better Polysemy type inference
- -fplugin=Polysemy.Plugin
