name:                shaunwhite
version:             0.1.0.0
github:              "typesafety/shaunwhite"
license:             MIT
author:              "Thomas Li"
maintainer:          "guslithd@student.gu.se"
copyright:           "2021 Thomas Li"

extra-source-files:
- README.md
- CHANGELOG.md

dependencies:
# Dependencies for the custom prelude
- base
- relude

# Other dependencies
- aeson
- calamity
- calamity-commands
- data-flags
- di
- di-polysemy
- directory
- filepath
- lens
- parseargs
- polysemy
- polysemy-plugin
- text

executables:
  shaunwhite-exe:
    main: Main.hs
    source-dirs: app
    dependencies:
    - shaunwhite
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -flate-specialise
    - -fspecialise-aggressively

    # To stop a warning caused by a hpack issue:
    # https://github.com/commercialhaskell/stack/issues/5439
    when:
    - condition: false
      other-modules: Paths_shaunwhite

# The majority of the code resides here, and is only separated from the
# "executables" to make Haddock generation easier.
library:
  source-dirs: lib/
  exposed-modules:
    - Args
    - Auth
    - Config
    - CustomPrelude
    - Env
    - Rolerequest
    - Shaunwhite

default-extensions:
# Disable implicit Prelude imports. Import the custom prelude instead.
- NoImplicitPrelude

- DataKinds
- FlexibleContexts
- GADTs
- ImportQualifiedPost
- LambdaCase
- OverloadedLabels
- OverloadedStrings
- PolyKinds
- RankNTypes
- ScopedTypeVariables
- TypeApplications
- TypeFamilies
- TypeOperators

ghc-options:
# Warnings
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wpartial-fields
- -Wredundant-constraints

# Plugin for better Polysemy type inference
- -fplugin=Polysemy.Plugin
